# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SankeyDiagram
                                 A QGIS plugin
 This plugin creates a Sankey Diagram from the relation of two attribute columns
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-08
        copyright            : (C) 2025 by mahlwerk
        email                : anas-unterwegs@posteo.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'mahlwerk'
__date__ = '2025-08-08'
__copyright__ = '(C) 2025 by mahlwerk'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SankeyDiagram class from file SankeyDiagram.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sankey_diagram_creator import SankeyDiagramPlugin
    return SankeyDiagramPlugin()
