# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SankeyDiagram
                                 A QGIS plugin
 This plugin creates a Sankey Diagram from the relation of two attribute columns
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-08
        copyright            : (C) 2025 by mahlwerk
        email                : anas-unterwegs@posteo.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'mahlwerk'
__date__ = '2025-08-08'
__copyright__ = '(C) 2025 by mahlwerk'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import (QgsProcessing,
                 QgsFeatureSink,
                 QgsProcessingAlgorithm,
                 QgsProcessingParameterFeatureSource,
                 QgsProcessingParameterFileDestination)
from .sankey_diagram_creator_provider import SankeyDiagramProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class SankeyDiagramPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = SankeyDiagramProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
